### ISSUE TITLE
Add logger for management

### ISSUE THREAD

**Issue by seven9nrh** [seven9nrh/gacha-java#6]

**Comment by gs16062021** [comment]
I would like to do it. Is there particular scenario?

**Comment by seven9nrh** [comment]
@gs16062021 
Thank you for reply.
Output the operation log with an interceptor to the database so that you can refer to the operation log with the management API.
Please comment if you have any good ideas.

**Comment by DevPJ9** [comment]
Hello, @seven9nrh I would like to contribute. Do you want to print logger info before database actions as references to catch any possible errors?
